

export enum MessageEventEnums{
    CONNECTED='CONNECTED',    
    NEW_USER='NEW_USER',
    MESSAGE_NOT_SENT="MESSAGE_NOT_SENT",
    RECEIVED_PERSONAL_MESSAGE='RECEIVED_PERSONAL_MESSAGE',    
    OK_SIGNAL='OK_SIGNAL',
    BAD_REQUEST='BAD_REQUEST',
    UNAUTHORIZED='UNAUTHORIZED'
}

export enum MessageStatusEnum{
    SENT='SENT',
    RECEIVED='RECEIVED',
    CONNECTED='CONNECTED',    
    ERROR='ERROR',
    OK=200,
    BAD_REQUEST=400,
    UNAUTHORIZED=401

}