
export enum MicroservicesNames{
    USER_SERVICE = "USER_SERVICE",
    POST_SERVICE = "POST_SERVICE",
    AUTH_SERVICE = "AUTH_SERVICE",
    AWS_SERVICE = "AWS_SERVICE",
    CHAT_SERVICE = "CHAT_SERVICE",
    NOTIFICATION_SERVICE = "NOTIFICATION_SERVICE"
}